
package examen;

import java.text.DecimalFormat;


public class examen_1 extends javax.swing.JFrame {

    /**
     * Creates new form Medi_Longi
     */
    public examen_1() {
        initComponents();

        this.setResizable(false); //codigo para bloquear la opcion de maximizar
        setLocationRelativeTo(null);//codigo para hacer que nuestro programa aparesca en el centro.

        //Código para poner icono a la aplicacion 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        comboPelicula = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combos = new javax.swing.JComboBox<>();
        unidad = new javax.swing.JTextField();
        comboPrecio = new javax.swing.JComboBox<>();
        calcular = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        cantidadPersonas = new javax.swing.JTextField();
        cantidadCombo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PELICULAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 250, 35));

        comboPelicula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelicula 1", "Pelicula 2", "Pelicula 3", "Pelicula 4", "Pelicula 5", "Pelicula 6" }));
        comboPelicula.setSelectedItem(comboPelicula);
        comboPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(comboPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 243, 30));

        resultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Peliculas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 103, 43));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Combos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 36));

        combos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Familiar", "Con la Pareja", "Con la pareja 2", "Con los amigos", "Con los amigos 2", "Individual" }));
        combos.setSelectedItem(combos);
        combos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosActionPerformed(evt);
            }
        });
        getContentPane().add(combos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 243, 30));

        unidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadActionPerformed(evt);
            }
        });
        getContentPane().add(unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 220, 30));

        comboPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboPrecio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niños menores a 3 años", "Niños Jovenes y Adultos", "Adultos mayores a 65 años" }));
        comboPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(comboPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        calcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calcular.setText("CALCULAR");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        cantidadPersonas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidadPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadPersonasActionPerformed(evt);
            }
        });
        getContentPane().add(cantidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 220, 30));

        cantidadCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidadCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadComboActionPerformed(evt);
            }
        });
        getContentPane().add(cantidadCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 220, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPeliculaActionPerformed
        double dato1, resultado;
        dato1 = Double.parseDouble(unidad.getText());
        String option = (String) comboPrecio.getSelectedItem();

        if (option.equals("Pelicula 1")) {
            resultado = dato1;
            cantidadPersonas.setText("" + resultado + " P1");
        }
        if (option.equals("Pelicula 2")) {
            resultado = dato1;
            cantidadPersonas.setText("" + resultado + "P2");
        }
        if (option.equals("Pelicula 3")) {
            resultado = dato1;
            cantidadPersonas.setText("" + resultado + " P3");
        }
        if (option.equals("Pelicula 4")) {
            resultado = dato1;
            cantidadPersonas.setText("" + resultado + " P4");
        }
        if (option.equals("Pelicula 5")) {
            resultado = dato1;
            cantidadPersonas.setText("" + resultado + " P5");
        }
        if (option.equals("Pelicula 6")) {
            resultado = dato1;
            cantidadPersonas.setText("" + resultado + " P6");
        }
    }//GEN-LAST:event_comboPeliculaActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void combosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosActionPerformed
        double dato1, resultado;
        dato1 = Double.parseDouble(cantidadCombo.getText());
        String option = (String) combos.getSelectedItem();

        if (option.equals("Familia")) {
            resultado = dato1 * 49.9;
            cantidadCombo.setText("" + resultado + " Opcion1");
        }
        if (option.equals("Con la pareja")) {
            resultado = dato1 * 30.9;
            cantidadCombo.setText("" + resultado + " Opcion2");
        }
        if (option.equals("Con la pareja 2")) {
            resultado = dato1 * 28.9;
            cantidadCombo.setText("" + resultado + " Opcion3");
        }
        if (option.equals("Con los amigos")) {
            resultado = dato1 * 35.9;
            cantidadCombo.setText("" + resultado + " Opcion4");
        }
        if (option.equals("Con los amigos 2 ")) {
            resultado = dato1 * 32.9;
            cantidadCombo.setText("" + resultado + " Opcion5");
        }
        if (option.equals("Individual")) {
            resultado = dato1 * 13.9;
            cantidadCombo.setText("" + resultado + " Opcion6");
        }
    }//GEN-LAST:event_combosActionPerformed

    private void unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        DecimalFormat df = new DecimalFormat("0.##");
        Double total = Double.parseDouble(cantidadPersonas.getText());
        Double combos = Double.parseDouble(cantidadCombo.getText());
        double monto = (total + combos);

        resultado.setText(String.valueOf(df.format(monto)));
        System.out.println(monto);


    }//GEN-LAST:event_calcularActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void comboPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrecioActionPerformed
        double dato1, resultado;
        dato1 = Double.parseDouble(cantidadCombo.getText());
        String option = (String) comboPrecio.getSelectedItem();

        if (option.equals("Niños menores a 3 años")) {
            resultado = dato1 * 4.5;
            cantidadCombo.setText("" + resultado + " Opcion1");
        }
        if (option.equals("Niños  Jóvenes y Adultos ")) {
            resultado = dato1 * 7.5;
            cantidadCombo.setText("" + resultado + " Opcion2");
        }
        if (option.equals("Adultos mayores de 65 años")) {
            resultado = dato1 * 5;
            cantidadCombo.setText("" + resultado + " Opcion3");
        }
    }//GEN-LAST:event_comboPrecioActionPerformed

    private void cantidadPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadPersonasActionPerformed

    private void cantidadComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examen_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examen_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcular;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidadCombo;
    private javax.swing.JTextField cantidadPersonas;
    private javax.swing.JComboBox<String> comboPelicula;
    private javax.swing.JComboBox<String> comboPrecio;
    private javax.swing.JComboBox<String> combos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField unidad;
    // End of variables declaration//GEN-END:variables
}
